### PR TITLE
fix: return a notfound err

### LINKED ISSUE #20513: juju 3.6.9 openstack provider regression when bootstrapping
### Description

With 3.6.9 when i bootstrap a controller using a network with `port_security_disabled = false` it fails because juju is trying to find a security group when running openSSH.

15:17:27 DEBUG goose logger.go:44 TRACE: MakeServiceURL: https://neutron.acme.com:9696/v2.0/security-groups?name=juju-67e72a20-ffbe-4db2-8cc8-340e3fabb4b1-d10d25f1-eeb8-4866-8abd-771853dd9a1e
15:17:27 ERROR juju.cmd.juju.commands bootstrap.go:1032 failed to bootstrap model: cannot open SSH: failed to find security group with name: juju-67e72a20-ffbe-4db2-8cc8-340e3fabb4b1-d10d25f1-eeb8-4866-8abd-771853dd9a1e
15:17:27 DEBUG juju.cmd.juju.commands bootstrap.go:1033 (error details: [{github.com/juju/juju/cmd/juju/commands.(*bootstrapCommand).Run:1131: failed to bootstrap model} {github.com/juju/juju/environs/bootstrap.Bootstrap:729: } {github.com/juju/juju/environs/bootstrap.bootstrapIAAS:597: } {github.com/juju/juju/provider/common.Bootstrap:63: } {github.com/juju/juju/provider/common.BootstrapInstance:299: cannot open SSH} {github.com/juju/juju/provider/openstack.(*Environ).OpenModelPorts:2152: } {github.com/juju/juju/provider/openstack.(*neutronFirewaller).OpenModelPorts:563: } {github.com/juju/juju/provider/openstack.(*neutronFirewaller).openPortsInGroup:692: } {github.com/juju/retry.Call:188: } {failed to find security group with name: juju-67e72a20-ffbe-4db2-8cc8-340e3fabb4b1-d10d25f1-eeb8-4866-8abd-771853dd9a1e}])

This worked fine in 3.6.8 and I suspect it may be related to the SG api efficiency fixes that landed in 3.6.9

### Juju version

3.6.9

### Cloud

OpenStack

### Expected behaviour

Juju should not attempt to use a security group when an OpenStack network with `port_security_disabled = false` is used.

### Reproduce / Test

#!/bin/bash -eux
: ${controller_name:=test}
: ${controller_series:=jammy}

declare -a model_config=()
declare -a model_defaults=( 'use-default-secgroup=true'
                            'network=net_psd'
                            'image-metadata-url=https://radosgw.acme.com:443/swift/v1/simplestreams/data/'
                           )
for d in ${model_defaults[@]}; do model_config+=( "--config $d" ); done
juju bootstrap --debug --verbose prodstack --bootstrap-series ${controller_series} ${model_config[@]} ${controller_name}
juju model-defaults ${model_defaults[@]}

### Notes & References

https://github.com/juju/juju/releases/tag/v3.6.9

### PR DESCRIPTION
**Pull request by adisazhar123**
Fixes [#20513](https://github.com/juju/juju/issues/20513). The calling client can utilize, `IsNotFound(err)`, as part of the Goose errors package to check that no security groups were found.
A PR in Juju is on the way.

https://warthogs.atlassian.net/browse/JUJU-8432

### CODE REVIEW

File: neutron/live_test.go [hunk 1]
```diff
@@ -234,8 +235,10 @@ func (s *LiveTests) TestSecurityGroupsV2(c *gc.C) {
 	if !found {
 		c.Errorf("expected to find added security group %s, when requested by name", updatedSecGroup.Name)
 	}
-	_, err = s.neutron.SecurityGroupByNameV2(newSecGrp.Name)
-	c.Assert(err, gc.Not(gc.IsNil))
+	nonExistingGroups, err := s.neutron.SecurityGroupByNameV2(newSecGrp.Name)
```
Comment (wallyworld) [inline neutron/live_test.go]: Don't need `nonExistingGroups`. Stick with `_, err := ...` and just check the error

File: neutron/live_test.go [hunk 2]
```diff
@@ -234,8 +235,10 @@ func (s *LiveTests) TestSecurityGroupsV2(c *gc.C) {
...
+	c.Assert(nonExistingGroups, gc.IsNil)
+	c.Assert(errors.IsNotFound(err), gc.Equals, true)
+	c.Assert(err, gc.ErrorMatches, "failed to find security group with name: SecurityGroupTest")
```
Comment (wallyworld) [inline neutron/live_test.go]: No need to check error message, just the type

**Review by wallyworld — APPROVED** [review]
Just some tweaks to tests

**Comment by adisazhar123** [comment]
@wallyworld thanks, changes addressed.
